"""add_autoparse_models_and_user_settings

Revision ID: 4ae5988f2049
Revises: e6864bbe0675
Create Date: 2026-03-09 17:47:11.054827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ae5988f2049'
down_revision: Union[str, None] = 'e6864bbe0675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoparse_companies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_title', sa.String(length=500), nullable=False),
    sa.Column('search_url', sa.Text(), nullable=False),
    sa.Column('keyword_filter', sa.String(length=500), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_vacancies_found', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autoparsed_vacancies',
    sa.Column('autoparse_company_id', sa.Integer(), nullable=False),
    sa.Column('hh_vacancy_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('company_url', sa.Text(), nullable=True),
    sa.Column('salary', sa.String(length=200), nullable=True),
    sa.Column('compensation_frequency', sa.String(length=200), nullable=True),
    sa.Column('work_experience', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=200), nullable=True),
    sa.Column('work_schedule', sa.String(length=200), nullable=True),
    sa.Column('working_hours', sa.String(length=200), nullable=True),
    sa.Column('work_formats', sa.String(length=200), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autoparse_company_id'], ['autoparse_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('autoparse_company_id', 'hh_vacancy_id', name='uq_autoparse_company_vacancy')
    )
    op.create_index(op.f('ix_autoparsed_vacancies_hh_vacancy_id'), 'autoparsed_vacancies', ['hh_vacancy_id'], unique=False)
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='Europe/Moscow'))
    op.add_column('users', sa.Column('autoparse_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'autoparse_settings')
    op.drop_column('users', 'timezone')
    op.drop_index(op.f('ix_autoparsed_vacancies_hh_vacancy_id'), table_name='autoparsed_vacancies')
    op.drop_table('autoparsed_vacancies')
    op.drop_table('autoparse_companies')
    # ### end Alembic commands ###
