"""add_uq_user_vacancy_context

Revision ID: abaf35cea4cc
Revises: dd5101b09d21
Create Date: 2026-03-06 21:37:13.850931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abaf35cea4cc'
down_revision: Union[str, None] = 'dd5101b09d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_vacancy_context', 'vacancy_blacklist', ['user_id', 'hh_vacancy_id', 'vacancy_title_context'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_vacancy_context', 'vacancy_blacklist', type_='unique')
    # ### end Alembic commands ###
